### ISSUE TITLE
Uncaught SyntaxError: Invalid regular expression: /return response.json(it/: Unterminated group

### ISSUE THREAD

**Issue by zahmee** [Tuchkata/styles-highlighter#7] opened 2017-08-23 17:00 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.3 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [styles-highlighter](https://github.com/Tuchkata/styles-highlighter) package 2.3.0

### Stack Trace

Uncaught SyntaxError: Invalid regular expression: /return response.json(it/: Unterminated group

```
At C:\Users\admin\.atom\packages\styles-highlighter\lib\styles-highlighter.coffee:79

SyntaxError: Invalid regular expression: /return response.json(it/: Unterminated group
    at new RegExp (<anonymous>)
    at Object.markSelection (/packages/styles-highlighter/lib/styles-highlighter.coffee:79:35)
    at Object.markSixthStyle (/packages/styles-highlighter/lib/styles-highlighter.coffee:111:6)
    at /packages/styles-highlighter/lib/styles-highlighter.coffee:37:101)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (~/AppData/Local/atom/app-1.19.3/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (~/AppData/Local/atom/app-1.19.3/resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.19.3/resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:19.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:11.9.0 styles-highlighter:markSixthStyle (span.syntax--keyword.syntax--control.syntax--statement.syntax--python)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-bracket-highlight 0.3.2 
atom-live-server 2.1.2 
atom-material-syntax 1.0.6 
autoclose-html 0.23.0 
autocomplete-modules 1.7.0 
autocomplete-paths 2.8.0 
busy-signal 1.4.3 
color-picker 2.2.5 
Delete-Whitelines 0.6.3 
double-tag 0.9.0 
emmet 2.4.3 
file-icons 2.1.11 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
jshint 1.8.6 
language-babel 2.72.0 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.6.7 
minimap 4.29.6 
monokai 0.24.0 
nord-atom-syntax 0.9.1 
open-terminal-here 2.3.1 
pigments 0.40.2 
Remote-FTP 1.1.4 
script 3.15.0 
seti-syntax 1.1.3 
styles-highlighter 2.3.0 
swackets 0.26.0 
tag 0.5.0 
vue-format 0.4.0 
vue2-autocomplete 0.1.0-alpha.4 
zentabs 0.8.8 
```

**Comment by oxygen0211** [comment] 2017-09-03 08:56
Looks like a duplicate of #4 to me

**Closed as completed by oxygen0211** 2017-09-03 08:56 UTC
